/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedPantryRouteImport } from './routes/_authenticated/pantry'
import { Route as AuthenticatedMoneyRouteImport } from './routes/_authenticated/money'
import { Route as AuthenticatedGroceryRouteImport } from './routes/_authenticated/grocery'

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/_authenticated/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPantryRoute = AuthenticatedPantryRouteImport.update({
  id: '/_authenticated/pantry',
  path: '/pantry',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMoneyRoute = AuthenticatedMoneyRouteImport.update({
  id: '/_authenticated/money',
  path: '/money',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedGroceryRoute = AuthenticatedGroceryRouteImport.update({
  id: '/_authenticated/grocery',
  path: '/grocery',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/grocery': typeof AuthenticatedGroceryRoute
  '/money': typeof AuthenticatedMoneyRoute
  '/pantry': typeof AuthenticatedPantryRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesByTo {
  '/grocery': typeof AuthenticatedGroceryRoute
  '/money': typeof AuthenticatedMoneyRoute
  '/pantry': typeof AuthenticatedPantryRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/grocery': typeof AuthenticatedGroceryRoute
  '/_authenticated/money': typeof AuthenticatedMoneyRoute
  '/_authenticated/pantry': typeof AuthenticatedPantryRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/grocery' | '/money' | '/pantry' | '/tasks' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/grocery' | '/money' | '/pantry' | '/tasks' | '/'
  id:
    | '__root__'
    | '/_authenticated/grocery'
    | '/_authenticated/money'
    | '/_authenticated/pantry'
    | '/_authenticated/tasks'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedGroceryRoute: typeof AuthenticatedGroceryRoute
  AuthenticatedMoneyRoute: typeof AuthenticatedMoneyRoute
  AuthenticatedPantryRoute: typeof AuthenticatedPantryRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pantry': {
      id: '/_authenticated/pantry'
      path: '/pantry'
      fullPath: '/pantry'
      preLoaderRoute: typeof AuthenticatedPantryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/money': {
      id: '/_authenticated/money'
      path: '/money'
      fullPath: '/money'
      preLoaderRoute: typeof AuthenticatedMoneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/grocery': {
      id: '/_authenticated/grocery'
      path: '/grocery'
      fullPath: '/grocery'
      preLoaderRoute: typeof AuthenticatedGroceryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedGroceryRoute: AuthenticatedGroceryRoute,
  AuthenticatedMoneyRoute: AuthenticatedMoneyRoute,
  AuthenticatedPantryRoute: AuthenticatedPantryRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
