/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedWeatherRouteImport } from './routes/_authenticated/weather'
import { Route as AuthenticatedVaultRouteImport } from './routes/_authenticated/vault'
import { Route as AuthenticatedTripsRouteImport } from './routes/_authenticated/trips'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedRecipesRouteImport } from './routes/_authenticated/recipes'
import { Route as AuthenticatedPantryRouteImport } from './routes/_authenticated/pantry'
import { Route as AuthenticatedMoneyRouteImport } from './routes/_authenticated/money'
import { Route as AuthenticatedFoodsRouteImport } from './routes/_authenticated/foods'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedTripsIndexRouteImport } from './routes/_authenticated/trips.index'
import { Route as AuthenticatedTripsPlacesRouteImport } from './routes/_authenticated/trips.places'
import { Route as AuthenticatedTripsBucketListRouteImport } from './routes/_authenticated/trips.bucket-list'
import { Route as AuthenticatedTripsTripIdRouteImport } from './routes/_authenticated/trips.$tripId'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicHooksProcessVaultRemindersRouteImport } from './routes/api/public/hooks/process-vault-reminders'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWeatherRoute = AuthenticatedWeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVaultRoute = AuthenticatedVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTripsRoute = AuthenticatedTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecipesRoute = AuthenticatedRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPantryRoute = AuthenticatedPantryRouteImport.update({
  id: '/pantry',
  path: '/pantry',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMoneyRoute = AuthenticatedMoneyRouteImport.update({
  id: '/money',
  path: '/money',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFoodsRoute = AuthenticatedFoodsRouteImport.update({
  id: '/foods',
  path: '/foods',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedTripsIndexRoute = AuthenticatedTripsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedTripsRoute,
} as any)
const AuthenticatedTripsPlacesRoute =
  AuthenticatedTripsPlacesRouteImport.update({
    id: '/places',
    path: '/places',
    getParentRoute: () => AuthenticatedTripsRoute,
  } as any)
const AuthenticatedTripsBucketListRoute =
  AuthenticatedTripsBucketListRouteImport.update({
    id: '/bucket-list',
    path: '/bucket-list',
    getParentRoute: () => AuthenticatedTripsRoute,
  } as any)
const AuthenticatedTripsTripIdRoute =
  AuthenticatedTripsTripIdRouteImport.update({
    id: '/$tripId',
    path: '/$tripId',
    getParentRoute: () => AuthenticatedTripsRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksProcessVaultRemindersRoute =
  ApiPublicHooksProcessVaultRemindersRouteImport.update({
    id: '/api/public/hooks/process-vault-reminders',
    path: '/api/public/hooks/process-vault-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/foods': typeof AuthenticatedFoodsRoute
  '/money': typeof AuthenticatedMoneyRoute
  '/pantry': typeof AuthenticatedPantryRoute
  '/recipes': typeof AuthenticatedRecipesRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/trips': typeof AuthenticatedTripsRouteWithChildren
  '/vault': typeof AuthenticatedVaultRoute
  '/weather': typeof AuthenticatedWeatherRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/trips/$tripId': typeof AuthenticatedTripsTripIdRoute
  '/trips/bucket-list': typeof AuthenticatedTripsBucketListRoute
  '/trips/places': typeof AuthenticatedTripsPlacesRoute
  '/trips/': typeof AuthenticatedTripsIndexRoute
  '/api/public/hooks/process-vault-reminders': typeof ApiPublicHooksProcessVaultRemindersRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/foods': typeof AuthenticatedFoodsRoute
  '/money': typeof AuthenticatedMoneyRoute
  '/pantry': typeof AuthenticatedPantryRoute
  '/recipes': typeof AuthenticatedRecipesRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/vault': typeof AuthenticatedVaultRoute
  '/weather': typeof AuthenticatedWeatherRoute
  '/': typeof AuthenticatedIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/trips/$tripId': typeof AuthenticatedTripsTripIdRoute
  '/trips/bucket-list': typeof AuthenticatedTripsBucketListRoute
  '/trips/places': typeof AuthenticatedTripsPlacesRoute
  '/trips': typeof AuthenticatedTripsIndexRoute
  '/api/public/hooks/process-vault-reminders': typeof ApiPublicHooksProcessVaultRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/foods': typeof AuthenticatedFoodsRoute
  '/_authenticated/money': typeof AuthenticatedMoneyRoute
  '/_authenticated/pantry': typeof AuthenticatedPantryRoute
  '/_authenticated/recipes': typeof AuthenticatedRecipesRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/trips': typeof AuthenticatedTripsRouteWithChildren
  '/_authenticated/vault': typeof AuthenticatedVaultRoute
  '/_authenticated/weather': typeof AuthenticatedWeatherRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/trips/$tripId': typeof AuthenticatedTripsTripIdRoute
  '/_authenticated/trips/bucket-list': typeof AuthenticatedTripsBucketListRoute
  '/_authenticated/trips/places': typeof AuthenticatedTripsPlacesRoute
  '/_authenticated/trips/': typeof AuthenticatedTripsIndexRoute
  '/api/public/hooks/process-vault-reminders': typeof ApiPublicHooksProcessVaultRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/calendar'
    | '/foods'
    | '/money'
    | '/pantry'
    | '/recipes'
    | '/tasks'
    | '/trips'
    | '/vault'
    | '/weather'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/trips/$tripId'
    | '/trips/bucket-list'
    | '/trips/places'
    | '/trips/'
    | '/api/public/hooks/process-vault-reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/calendar'
    | '/foods'
    | '/money'
    | '/pantry'
    | '/recipes'
    | '/tasks'
    | '/vault'
    | '/weather'
    | '/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/trips/$tripId'
    | '/trips/bucket-list'
    | '/trips/places'
    | '/trips'
    | '/api/public/hooks/process-vault-reminders'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/calendar'
    | '/_authenticated/foods'
    | '/_authenticated/money'
    | '/_authenticated/pantry'
    | '/_authenticated/recipes'
    | '/_authenticated/tasks'
    | '/_authenticated/trips'
    | '/_authenticated/vault'
    | '/_authenticated/weather'
    | '/_authenticated/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/trips/$tripId'
    | '/_authenticated/trips/bucket-list'
    | '/_authenticated/trips/places'
    | '/_authenticated/trips/'
    | '/api/public/hooks/process-vault-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicHooksProcessVaultRemindersRoute: typeof ApiPublicHooksProcessVaultRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/weather': {
      id: '/_authenticated/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof AuthenticatedWeatherRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vault': {
      id: '/_authenticated/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof AuthenticatedVaultRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trips': {
      id: '/_authenticated/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof AuthenticatedTripsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recipes': {
      id: '/_authenticated/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof AuthenticatedRecipesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pantry': {
      id: '/_authenticated/pantry'
      path: '/pantry'
      fullPath: '/pantry'
      preLoaderRoute: typeof AuthenticatedPantryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/money': {
      id: '/_authenticated/money'
      path: '/money'
      fullPath: '/money'
      preLoaderRoute: typeof AuthenticatedMoneyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/foods': {
      id: '/_authenticated/foods'
      path: '/foods'
      fullPath: '/foods'
      preLoaderRoute: typeof AuthenticatedFoodsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trips/': {
      id: '/_authenticated/trips/'
      path: '/'
      fullPath: '/trips/'
      preLoaderRoute: typeof AuthenticatedTripsIndexRouteImport
      parentRoute: typeof AuthenticatedTripsRoute
    }
    '/_authenticated/trips/places': {
      id: '/_authenticated/trips/places'
      path: '/places'
      fullPath: '/trips/places'
      preLoaderRoute: typeof AuthenticatedTripsPlacesRouteImport
      parentRoute: typeof AuthenticatedTripsRoute
    }
    '/_authenticated/trips/bucket-list': {
      id: '/_authenticated/trips/bucket-list'
      path: '/bucket-list'
      fullPath: '/trips/bucket-list'
      preLoaderRoute: typeof AuthenticatedTripsBucketListRouteImport
      parentRoute: typeof AuthenticatedTripsRoute
    }
    '/_authenticated/trips/$tripId': {
      id: '/_authenticated/trips/$tripId'
      path: '/$tripId'
      fullPath: '/trips/$tripId'
      preLoaderRoute: typeof AuthenticatedTripsTripIdRouteImport
      parentRoute: typeof AuthenticatedTripsRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-vault-reminders': {
      id: '/api/public/hooks/process-vault-reminders'
      path: '/api/public/hooks/process-vault-reminders'
      fullPath: '/api/public/hooks/process-vault-reminders'
      preLoaderRoute: typeof ApiPublicHooksProcessVaultRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedTripsRouteChildren {
  AuthenticatedTripsTripIdRoute: typeof AuthenticatedTripsTripIdRoute
  AuthenticatedTripsBucketListRoute: typeof AuthenticatedTripsBucketListRoute
  AuthenticatedTripsPlacesRoute: typeof AuthenticatedTripsPlacesRoute
  AuthenticatedTripsIndexRoute: typeof AuthenticatedTripsIndexRoute
}

const AuthenticatedTripsRouteChildren: AuthenticatedTripsRouteChildren = {
  AuthenticatedTripsTripIdRoute: AuthenticatedTripsTripIdRoute,
  AuthenticatedTripsBucketListRoute: AuthenticatedTripsBucketListRoute,
  AuthenticatedTripsPlacesRoute: AuthenticatedTripsPlacesRoute,
  AuthenticatedTripsIndexRoute: AuthenticatedTripsIndexRoute,
}

const AuthenticatedTripsRouteWithChildren =
  AuthenticatedTripsRoute._addFileChildren(AuthenticatedTripsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedFoodsRoute: typeof AuthenticatedFoodsRoute
  AuthenticatedMoneyRoute: typeof AuthenticatedMoneyRoute
  AuthenticatedPantryRoute: typeof AuthenticatedPantryRoute
  AuthenticatedRecipesRoute: typeof AuthenticatedRecipesRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedTripsRoute: typeof AuthenticatedTripsRouteWithChildren
  AuthenticatedVaultRoute: typeof AuthenticatedVaultRoute
  AuthenticatedWeatherRoute: typeof AuthenticatedWeatherRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedFoodsRoute: AuthenticatedFoodsRoute,
  AuthenticatedMoneyRoute: AuthenticatedMoneyRoute,
  AuthenticatedPantryRoute: AuthenticatedPantryRoute,
  AuthenticatedRecipesRoute: AuthenticatedRecipesRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedTripsRoute: AuthenticatedTripsRouteWithChildren,
  AuthenticatedVaultRoute: AuthenticatedVaultRoute,
  AuthenticatedWeatherRoute: AuthenticatedWeatherRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicHooksProcessVaultRemindersRoute:
    ApiPublicHooksProcessVaultRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
