/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedWeatherRouteImport } from './routes/_authenticated/weather'
import { Route as AuthenticatedVaultRouteImport } from './routes/_authenticated/vault'
import { Route as AuthenticatedTripsRouteImport } from './routes/_authenticated/trips'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedRecipesRouteImport } from './routes/_authenticated/recipes'
import { Route as AuthenticatedPantryRouteImport } from './routes/_authenticated/pantry'
import { Route as AuthenticatedMoneyRouteImport } from './routes/_authenticated/money'
import { Route as AuthenticatedFoodsRouteImport } from './routes/_authenticated/foods'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as ApiPublicHooksProcessVaultRemindersRouteImport } from './routes/api/public/hooks/process-vault-reminders'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWeatherRoute = AuthenticatedWeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVaultRoute = AuthenticatedVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTripsRoute = AuthenticatedTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecipesRoute = AuthenticatedRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPantryRoute = AuthenticatedPantryRouteImport.update({
  id: '/pantry',
  path: '/pantry',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMoneyRoute = AuthenticatedMoneyRouteImport.update({
  id: '/money',
  path: '/money',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFoodsRoute = AuthenticatedFoodsRouteImport.update({
  id: '/foods',
  path: '/foods',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicHooksProcessVaultRemindersRoute =
  ApiPublicHooksProcessVaultRemindersRouteImport.update({
    id: '/api/public/hooks/process-vault-reminders',
    path: '/api/public/hooks/process-vault-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/foods': typeof AuthenticatedFoodsRoute
  '/money': typeof AuthenticatedMoneyRoute
  '/pantry': typeof AuthenticatedPantryRoute
  '/recipes': typeof AuthenticatedRecipesRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/trips': typeof AuthenticatedTripsRoute
  '/vault': typeof AuthenticatedVaultRoute
  '/weather': typeof AuthenticatedWeatherRoute
  '/api/public/hooks/process-vault-reminders': typeof ApiPublicHooksProcessVaultRemindersRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/foods': typeof AuthenticatedFoodsRoute
  '/money': typeof AuthenticatedMoneyRoute
  '/pantry': typeof AuthenticatedPantryRoute
  '/recipes': typeof AuthenticatedRecipesRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/trips': typeof AuthenticatedTripsRoute
  '/vault': typeof AuthenticatedVaultRoute
  '/weather': typeof AuthenticatedWeatherRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/public/hooks/process-vault-reminders': typeof ApiPublicHooksProcessVaultRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/foods': typeof AuthenticatedFoodsRoute
  '/_authenticated/money': typeof AuthenticatedMoneyRoute
  '/_authenticated/pantry': typeof AuthenticatedPantryRoute
  '/_authenticated/recipes': typeof AuthenticatedRecipesRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/trips': typeof AuthenticatedTripsRoute
  '/_authenticated/vault': typeof AuthenticatedVaultRoute
  '/_authenticated/weather': typeof AuthenticatedWeatherRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/public/hooks/process-vault-reminders': typeof ApiPublicHooksProcessVaultRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calendar'
    | '/foods'
    | '/money'
    | '/pantry'
    | '/recipes'
    | '/tasks'
    | '/trips'
    | '/vault'
    | '/weather'
    | '/api/public/hooks/process-vault-reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/calendar'
    | '/foods'
    | '/money'
    | '/pantry'
    | '/recipes'
    | '/tasks'
    | '/trips'
    | '/vault'
    | '/weather'
    | '/'
    | '/api/public/hooks/process-vault-reminders'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/calendar'
    | '/_authenticated/foods'
    | '/_authenticated/money'
    | '/_authenticated/pantry'
    | '/_authenticated/recipes'
    | '/_authenticated/tasks'
    | '/_authenticated/trips'
    | '/_authenticated/vault'
    | '/_authenticated/weather'
    | '/_authenticated/'
    | '/api/public/hooks/process-vault-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksProcessVaultRemindersRoute: typeof ApiPublicHooksProcessVaultRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/weather': {
      id: '/_authenticated/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof AuthenticatedWeatherRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vault': {
      id: '/_authenticated/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof AuthenticatedVaultRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trips': {
      id: '/_authenticated/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof AuthenticatedTripsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recipes': {
      id: '/_authenticated/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof AuthenticatedRecipesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pantry': {
      id: '/_authenticated/pantry'
      path: '/pantry'
      fullPath: '/pantry'
      preLoaderRoute: typeof AuthenticatedPantryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/money': {
      id: '/_authenticated/money'
      path: '/money'
      fullPath: '/money'
      preLoaderRoute: typeof AuthenticatedMoneyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/foods': {
      id: '/_authenticated/foods'
      path: '/foods'
      fullPath: '/foods'
      preLoaderRoute: typeof AuthenticatedFoodsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/process-vault-reminders': {
      id: '/api/public/hooks/process-vault-reminders'
      path: '/api/public/hooks/process-vault-reminders'
      fullPath: '/api/public/hooks/process-vault-reminders'
      preLoaderRoute: typeof ApiPublicHooksProcessVaultRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedFoodsRoute: typeof AuthenticatedFoodsRoute
  AuthenticatedMoneyRoute: typeof AuthenticatedMoneyRoute
  AuthenticatedPantryRoute: typeof AuthenticatedPantryRoute
  AuthenticatedRecipesRoute: typeof AuthenticatedRecipesRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedTripsRoute: typeof AuthenticatedTripsRoute
  AuthenticatedVaultRoute: typeof AuthenticatedVaultRoute
  AuthenticatedWeatherRoute: typeof AuthenticatedWeatherRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedFoodsRoute: AuthenticatedFoodsRoute,
  AuthenticatedMoneyRoute: AuthenticatedMoneyRoute,
  AuthenticatedPantryRoute: AuthenticatedPantryRoute,
  AuthenticatedRecipesRoute: AuthenticatedRecipesRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedTripsRoute: AuthenticatedTripsRoute,
  AuthenticatedVaultRoute: AuthenticatedVaultRoute,
  AuthenticatedWeatherRoute: AuthenticatedWeatherRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksProcessVaultRemindersRoute:
    ApiPublicHooksProcessVaultRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
